# External gems
gems:
  - jekyll-sitemap

exclude:
  - "/vendor/"

# Site settings
title: Eing Ong
subtitle: "Capturing my learnings to share and remember"
#email: eing.ong@intuit.com
name: Eing Ong
description: > 
  <i>“I must judge for myself,
   but how can I judge, how can any man judge,
   unless his mind has been opened and enlarged by reading.”</i>
  – John Adams
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://eing.github.io" # the base hostname & protocol for your site
cover: "assets/header_image.jpg"
logo: "assets/logo.png"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
paginate: 5
paginate_path: "/page:num/"

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
#jekyll-archives: 
#  enabled:
#    - categories
#    - tags
#  layout: archive
#  permalinks:
#    category: '/category/:name/'
#    tag: '/tag/:name/'

# Disqus comments
disqus_shortname: eing

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: Technology
    desc: "Posts on technology."

  - cat: Testing
    desc: "Posts on software testing."

  - cat: Conferences
    desc: "Posts on conferences highlights."

# Social icons and sharing options
#
# Social settings are used in two places:
# * In the footer, as links to your personal profiles
# * After each blog post for sharing widgets
# 
# Example:
# 
# social:
#   - name: Twitter                         # Name of the service
#     icon: twitter                         # Font Awesome icon to use (minus fa- prefix)
#     username: "@TheBenCentra"             # (User) Name to display in the footer link
#     url: https://twitter.com/TheBenCentra # URL of your profile (leave blank to not display in footer)
#     desc: Follow me on Twitter            # Description to display as link title, etc
#     share: true                           # Include in the "Share" section of posts
social:
  - name: Twitter
    icon: twitter
    username: eingong
    url: https://twitter.com/eingong
    desc: Follow me on Twitter
    share: true

  - name: GitHub
    icon: github
    username: eing
    url: https://github.com/eing
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Eing Ong
    url: https://www.linkedin.com/in/eingong
    desc: Connect with me on LinkedIn
    share: true

  - name: YouTube
    icon: youtube
    username: 
    url: 
    desc: Subscribe on YouTube
    share: false

# Social sharing protocols
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
#    fb_image: "assets/logo.png"
#    fb_image_width: 612
#    fb_image_height: 605
#    fb_image_type: "image/png"

    twitter_image: "assets/logo.png"

#    os_repo: "https://github.com/RichardLitt/wordhoardpress.com"
#    os_rcs_type: "git"
#    os_src: "git@github.com:RichardLitt/wordhoardpress.com.git"
