# External gems
gems:
  - jekyll-sitemap

exclude:
- "/vendor/"

title: Veena's Home Page!
subtitle: "Capturing my project updates"

social:
  - name: GitHub
    icon: github
    username: eing
    url: https://github.com/veenaguru
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Veena Gurumurthy
    url: https://www.linkedin.com/in/veena-gurumurthy-470a453
    desc: Connect with me on LinkedIn
share: true
